In [1]:
?array

array                   package:base                   R Documentation

_M_u_l_t_i-_w_a_y _A_r_r_a_y_s

_D_e_s_c_r_i_p_t_i_o_n:

     Creates or tests for arrays.

_U_s_a_g_e:

     array(data = NA, dim = length(data), dimnames = NULL)
     as.array(x, ...)
     is.array(x)
     
_A_r_g_u_m_e_n_t_s:

    data: a vector (including a list or 'expression' vector) giving
          data to fill the array.  Non-atomic classed objects are
          coerced by 'as.vector'.

     dim: the dim attribute for the array to be created, that is an
          integer vector of length one or more giving the maximal
          indices in each dimension.

dimnames: either 'NULL' or the names for the dimensions.  This must a
          list (or it will be ignored) with one component for each
          dimension, either 'NULL' or a character vector of the length
          given by 'dim' for that dimension.  The list can be named,
          and the list names will be used as names for the dimensions.
          If the list is shorter than the number of dimensions, it is
          extended by 'NULL's to the length required.

       x: an R object.

     ...: additional arguments to be passed to or from methods.

_D_e_t_a_i_l_s:

     An array in R can have one, two or more dimensions.  It is simply
     a vector which is stored with additional attributes giving the
     dimensions (attribute '"dim"') and optionally names for those
     dimensions (attribute '"dimnames"').

     A two-dimensional array is the same thing as a 'matrix'.

     One-dimensional arrays often look like vectors, but may be handled
     differently by some functions: 'str' does distinguish them in
     recent versions of R.

     The '"dim"' attribute is an integer vector of length one or more
     containing non-negative values: the product of the values must
     match the length of the array.

     The '"dimnames"' attribute is optional: if present it is a list
     with one component for each dimension, either 'NULL' or a
     character vector of the length given by the element of the '"dim"'
     attribute for that dimension.

     'is.array' is a primitive function.

     For a list array, the 'print' methods prints entries of length not
     one in the form 'integer,7' indicating the type and length.

_V_a_l_u_e:

     'array' returns an array with the extents specified in 'dim' and
     naming information in 'dimnames'.  The values in 'data' are taken
     to be those in the array with the leftmost subscript moving
     fastest.  If there are too few elements in 'data' to fill the
     array, then the elements in 'data' are recycled.  If 'data' has
     length zero, 'NA' of an appropriate type is used for atomic
     vectors ('0' for raw vectors) and 'NULL' for lists.

     Unlike 'matrix', 'array' does not currently remove any attributes
     left by 'as.vector' from a classed list 'data', so can return a
     list array with a class attribute.

     'as.array' is a generic function for coercing to arrays.  The
     default method does so by attaching a 'dim' attribute to it.  It
     also attaches 'dimnames' if 'x' has 'names'.  The sole purpose of
     this is to make it possible to access the 'dim[names]' attribute
     at a later time.

     'is.array' returns 'TRUE' or 'FALSE' depending on whether its
     argument is an array (i.e., has a 'dim' attribute of positive
     length) or not.  It is generic: you can write methods to handle
     specific classes of objects, see InternalMethods.

_N_o_t_e:

     'is.array' is a primitive function.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     'aperm', 'matrix', 'dim', 'dimnames'.

_E_x_a_m_p_l_e_s:

     dim(as.array(letters))
     array(1:3, c(2,4)) # recycle 1:3 "2 2/3 times"
     #     [,1] [,2] [,3] [,4]
     #[1,]    1    3   

In [3]:
student.scores <- array(c(23, 56, 67, 78, 90, 45, 67), dim=c(3,2))
student.scores

[,1] [,2]
[1,] 23   78  
[2,] 56   90  
[3,] 67   45

In [5]:
class(student.scores)

[1] "matrix"

In [7]:
is.matrix(student.scores)

[1] TRUE

In [13]:
is.array(student.scores) #Every matrix is a 2D array, but all arrays are not matrix

[1] TRUE

In [15]:
is.vector(student.scores) 

[1] FALSE

In [23]:
student.scores.midterm <- array(c(23, 56, 67, 78, 90, 45, 67), dim=c(3,2),
                       dimnames = list(c('Julia', 'James', 'Peter'), c('Math', 'English')))
student.scores.midterm

Math English
Julia 23   78     
James 56   90     
Peter 67   45

In [25]:
student.scores.endterm <- array(c(45, 56, 68, 100, 95, 55, 77), dim=c(3,2),
                       dimnames = list(c('Julia', 'James', 'Peter'), c('Math', 'English')))
student.scores.endterm

Math English
Julia 45   100    
James 56    95    
Peter 68    55

In [29]:
all.scores <- array(c(student.scores.midterm, student.scores.endterm), dim = c(3,2,2))
all.scores

, , 1

     [,1] [,2]
[1,]   23   78
[2,]   56   90
[3,]   67   45

, , 2

     [,1] [,2]
[1,]   45  100
[2,]   56   95
[3,]   68   55

In [31]:
print(all.scores)

, , 1

     [,1] [,2]
[1,]   23   78
[2,]   56   90
[3,]   67   45

, , 2

     [,1] [,2]
[1,]   45  100
[2,]   56   95
[3,]   68   55



In [37]:
all.scores <- array(c(student.scores.midterm, student.scores.endterm), dim = c(3,2,2),
                   dimnames = list(c('Julia', 'James', 'Peter'), c('Math', 'English'), c('Midterm', 'Endterm')))
print(all.scores)

, , Midterm

      Math English
Julia   23      78
James   56      90
Peter   67      45

, , Endterm

      Math English
Julia   45     100
James   56      95
Peter   68      55



In [39]:
is.matrix(all.scores)

[1] FALSE

In [41]:
is.array(all.scores)

[1] TRUE

In [43]:
dim(all.scores)

[1] 3 2 2

In [45]:
all.scores[1,1,1]

[1] 23

In [51]:
all.scores['James', ,'Endterm']

Math English 
     56      95

In [57]:
all.scores['James','Math',]

Midterm Endterm 
     56      56

In [61]:
all.scores[,,'Endterm'] <- all.scores[,,'Endterm'] * 1.1
print(all.scores)

, , Midterm

      Math English
Julia   23      78
James   56      90
Peter   67      45

, , Endterm

      Math English
Julia 49.5   110.0
James 61.6   104.5
Peter 74.8    60.5

