In [1]:
?matrix

matrix                  package:base                   R Documentation

_M_a_t_r_i_c_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     'matrix' creates a matrix from the given set of values.

     'as.matrix' attempts to turn its argument into a matrix.

     'is.matrix' tests if its argument is a (strict) matrix.

_U_s_a_g_e:

     matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
            dimnames = NULL)
     
     as.matrix(x, ...)
     ## S3 method for class 'data.frame'
     as.matrix(x, rownames.force = NA, ...)
     
     is.matrix(x)
     
_A_r_g_u_m_e_n_t_s:

    data: an optional data vector (including a list or 'expression'
          vector).  Non-atomic classed R objects are coerced by
          'as.vector' and all attributes discarded.

    nrow: the desired number of rows.

    ncol: the desired number of columns.

   byrow: logical. If 'FALSE' (the default) the matrix is filled by
          columns, otherwise the matrix is filled by rows.

dimnames: A 'dimnames' attribute for the matrix: 'NULL' or a 'list' of
          length 2 giving the row and column names respectively.  An
          empty list is treated as 'NULL', and a list of length one as
          row names.  The list can be named, and the list names will be
          used as names for the dimensions.

       x: an R object.

     ...: additional arguments to be passed to or from methods.

rownames.force: logical indicating if the resulting matrix should have
          character (rather than 'NULL') 'rownames'.  The default,
          'NA', uses 'NULL' rownames if the data frame has 'automatic'
          row.names or for a zero-row data frame.

_D_e_t_a_i_l_s:

     If one of 'nrow' or 'ncol' is not given, an attempt is made to
     infer it from the length of 'data' and the other parameter.  If
     neither is given, a one-column matrix is returned.

     If there are too few elements in 'data' to fill the matrix, then
     the elements in 'data' are recycled.  If 'data' has length zero,
     'NA' of an appropriate type is used for atomic vectors ('0' for
     raw vectors) and 'NULL' for lists.

     'is.matrix' returns 'TRUE' if 'x' is a vector and has a '"dim"'
     attribute of length 2 and 'FALSE' otherwise.  Note that a
     'data.frame' is *not* a matrix by this test.  The function is
     generic: you can write methods to handle specific classes of
     objects, see InternalMethods.

     'as.matrix' is a generic function.  The method for data frames
     will return a character matrix if there is only atomic columns and
     any non-(numeric/logical/complex) column, applying 'as.vector' to
     factors and 'format' to other non-character columns.  Otherwise,
     the usual coercion hierarchy (logical < integer < double <
     complex) will be used, e.g., all-logical data frames will be
     coerced to a logical matrix, mixed logical-integer will give a
     integer matrix, etc.

     The default method for 'as.matrix' calls 'as.vector(x)', and hence
     e.g. coerces factors to character vectors.

     When coercing a vector, it produces a one-column matrix, and
     promotes the names (if any) of the vector to the rownames of the
     matrix.

     'is.matrix' is a primitive function.

     The 'print' method for a matrix gives a rectangular layout with
     dimnames or indices.  For a list matrix, the entries of length not
     one are printed in the form 'integer,7' indicating the type and
     length.

_N_o_t_e:

     If you just want to convert a vector to a matrix, something like
     
       dim(x) <- c(nx, ny)
       dimnames(x) <- list(row_names, col_names)

     will avoid duplicating 'x'.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     'data.matrix', which attempts to convert to a numeric matrix.

     A matrix is the special case of a two-dimensional 'array'.

_E_x_a

In [3]:
matrix.a <- matrix(c(100, 200, 300, 400), ncol = 2)
matrix.a

[,1] [,2]
[1,] 100  300 
[2,] 200  400

In [9]:
matrix.b <- matrix(c(100, 200, 300, 400, 500, 600), ncol = 3, nrow = 2)
matrix.b

[,1] [,2] [,3]
[1,] 100  300  500 
[2,] 200  400  600

In [11]:
class(matrix.a)

[1] "matrix"

In [13]:
is.matrix(matrix.a)

[1] TRUE

In [15]:
matrix.a[1,2]

[1] 300

In [19]:
matrix.b[2,3]

[1] 600

In [27]:
mdat <- matrix(c(1,2,3, 11,12,13), nrow = 2, ncol = 3, byrow = TRUE,
               dimnames = list(c("row1", "row2"),
                               c("C.1", "C.2", "C.3")))
mdat

C.1 C.2 C.3
row1  1   2   3 
row2 11  12  13

In [29]:
matrix.a[2,2] <- 444
matrix.a

[,1] [,2]
[1,] 100  300 
[2,] 200  444

In [31]:
matrix.c <- matrix(nrow = 3, ncol = 4)
matrix.c

[,1] [,2] [,3] [,4]
[1,] NA   NA   NA   NA  
[2,] NA   NA   NA   NA  
[3,] NA   NA   NA   NA

In [43]:
matrix.d <- matrix(c(111, 222, 333, 444, 555, 666), nrow = 2, byrow = FALSE)
matrix.d

[,1] [,2] [,3]
[1,] 111  333  555 
[2,] 222  444  666

In [45]:
matrix.d <- matrix(c(111, 222, 333, 444, 555, 666), nrow = 2, byrow = TRUE)
matrix.d

[,1] [,2] [,3]
[1,] 111  222  333 
[2,] 444  555  666

In [49]:
matrix.e <- matrix(c(111, 222, 333, 444, 555, 666), nrow = 2, byrow = TRUE,
                  dimnames = list(c('row1', 'row2'), c('col1', 'col2', 'col3')))
matrix.e

col1 col2 col3
row1 111  222  333 
row2 444  555  666

In [51]:
dim(matrix.e)

[1] 2 3

In [53]:
nrow(matrix.e)

[1] 2

In [55]:
ncol(matrix.e)

[1] 3

In [57]:
length(matrix.e)

[1] 6

In [59]:
rownames(matrix.e)

[1] "row1" "row2"

In [61]:
colnames(matrix.e)

[1] "col1" "col2" "col3"

In [63]:
dimnames(matrix.e)

[[1]]
[1] "row1" "row2"

[[2]]
[1] "col1" "col2" "col3"

In [67]:
fruits <- matrix(c(4,5,3,6,8,6,8,9,5), c(3,3),
                dimnames = list(c('Apples', 'Oranges', 'Bananas'), c('Organic', 'Regular', 'Local')))
fruits

Organic Regular Local
Apples  4       6       8    
Oranges 5       8       9    
Bananas 3       6       5

In [69]:
fruits[1,3]

[1] 8

In [71]:
fruits[-1,3]

Oranges Bananas 
      9       5

In [75]:
fruits[3, c('Organic', 'Regular')]

Organic Regular 
      3       6

In [83]:
fruits[c('Apples', 'Oranges'), 1:2]

Organic Regular
Apples  4       6      
Oranges 5       8

In [85]:
a <- matrix(c(100, 200, 300, 400), nrow=2, ncol=2)
a

[,1] [,2]
[1,] 100  300 
[2,] 200  400

In [93]:
b <- matrix(nrow=3, ncol=3)
b

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA  
[3,] NA   NA   NA

In [97]:
b[2:3, 2:3] <- a
b

[,1] [,2] [,3]
[1,] NA    NA   NA 
[2,] NA   100  300 
[3,] NA   200  400

In [99]:
a <- matrix(c(10, 20, 30, 40), nrow=2, ncol=2)
a

[,1] [,2]
[1,] 10   30  
[2,] 20   40

In [101]:
a * 2

[,1] [,2]
[1,] 20   60  
[2,] 40   80

In [103]:
a / 3

[,1]     [,2]    
[1,] 3.333333 10.00000
[2,] 6.666667 13.33333

In [105]:
b <- matrix(c(1, 2, 3, 4), nrow=2, ncol=2)
b

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [107]:
a + b

[,1] [,2]
[1,] 11   33  
[2,] 22   44

In [109]:
a - b

[,1] [,2]
[1,]  9   27  
[2,] 18   36

In [111]:
a * b

[,1] [,2]
[1,] 10    90 
[2,] 40   160

In [113]:
a / b

[,1] [,2]
[1,] 10   10  
[2,] 10   10

In [115]:
a %/% b

[,1] [,2]
[1,] 10   10  
[2,] 10   10

In [117]:
a %% b

[,1] [,2]
[1,] 0    0   
[2,] 0    0

In [119]:
c <- matrix(1:6, nrow = 2)
c

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [127]:
a + c

ERROR: Error in a + c: non-conformable arrays


In [140]:
a # 2x2 matrix

[,1] [,2]
[1,] 10   30  
[2,] 20   40

In [142]:
c # 2x3 matrix

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [146]:
a %*% c # row of matrix 1 should be equal to col of matrix 2

[,1] [,2] [,3]
[1,]  70  150  230 
[2,] 100  220  340

In [148]:
result = a %*% c
result

[,1] [,2] [,3]
[1,]  70  150  230 
[2,] 100  220  340

In [150]:
identical(c, result)

[1] FALSE

In [152]:
d <- matrix(c(70,150,230,100,220,340), nrow = 2, byrow = TRUE)
d

[,1] [,2] [,3]
[1,]  70  150  230 
[2,] 100  220  340

In [160]:
dim(d) <- c(3,2)
d

[,1] [,2]
[1,]  70  220 
[2,] 100  230 
[3,] 150  340

In [162]:
a

[,1] [,2]
[1,] 10   30  
[2,] 20   40

In [164]:
c

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [168]:
combined <- c(a, c)
print(combined)

 [1] 10 20 30 40  1  2  3  4  5  6


In [170]:
columbined <- cbind(a, c)
columbined

[,1] [,2] [,3] [,4] [,5]
[1,] 10   30   1    3    5   
[2,] 20   40   2    4    6

In [176]:
rowbined <- rbind(a, c)
rowbined

ERROR: Error in rbind(a, c): number of columns of matrices must match (see arg 2)


In [184]:
transc <- t(c)

In [192]:
rowbind <- rbind(a, transc)
rowbind

[,1] [,2]
[1,] 10   30  
[2,] 20   40  
[3,]  1    2  
[4,]  3    4  
[5,]  5    6

In [194]:
dim(rowbind) <- c(2,5)
rowbind

[,1] [,2] [,3] [,4] [,5]
[1,] 10   1     5   40   4   
[2,] 20   3    30    2   6

In [196]:
dim(rowbind) <- c(2,4)
rowbind

ERROR: Error in dim(rowbind) <- c(2, 4): dims [product 8] do not match the length of object [10]


In [202]:
reduced <- rowbind[1, 1:3]
reduced

[1] 10  1  5

In [204]:
class(reduced)

[1] "numeric"

In [206]:
reduced <- rowbind[1, 1:3, drop=FALSE]
reduced

[,1] [,2] [,3]
[1,] 10   1    5

In [208]:
class(reduced)

[1] "matrix"

In [220]:
weight <- c(34,45,67,89,23,45,67,89,76)
weight

[1] 34 45 67 89 23 45 67 89 76

In [222]:
w <- matrix(weight, nrow = 3, ncol = 3, byrow = TRUE,
                  dimnames = list(c('row1', 'row2', 'row3'), c('col1', 'col2', 'col3')))
w

col1 col2 col3
row1 34   45   67  
row2 89   23   45  
row3 67   89   76

In [226]:
rowSums(w)

row1 row2 row3 
 146  157  232

In [228]:
colSums(w)

col1 col2 col3 
 190  157  188

In [230]:
rowMeans(w)

row1     row2     row3 
48.66667 52.33333 77.33333

In [232]:
colMeans(w)

col1     col2     col3 
63.33333 52.33333 62.66667

In [234]:
random <- matrix(c(1, TRUE, 'isable', 3+2i), nrow=2)
random

[,1] [,2]  
[1,] 1    isable
[2,] TRUE 3+2i